### ISSUE TITLE
2019 Q3 - MidQuarter OKR Scoring

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#1010]
It is the time of the quarter ⏱ where we check in on progress and chart our trajectory for the rest of the quarter (i.e. course correct to get back on track or intentionally drop KRs to focus remaining efforts).

@ipfs/wg-captains (+@raulk) - y'all have done this before, nevertheless here's the ask for each WG:

1. Update scores in the [IPFS Q3 OKRs sheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1681757723) - everyone should fill in the rows that they own
    * `Mid-Q Actual` - How much progress you have made on this KR
    * `Mid-Q Projection` - How much progress you believe you will have made by the end of the quarter
    * `Notes on grading` - An update on why you gave it this score (if not obvious)
2. Check the box below for your WG
3. Comment on this issue, with a few sentences to recap
4. Review progress and help individual contributors reallocate energy to the highest priority, highest impact KRs
5. Check in on the results during your next WG Weekly Sync and carry on for the rest of the quarter 🚀

**Checklist:**
- [x] [Bifrost (aka IPFS as a Service)](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1439867466)
- [x] [Testing Infra](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=96566767)
- [x] [Project Operations](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1562851442)
- [ ] [Package Managers](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1685270127)
- [x] [Documentation & Developer UX](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909)

If anyone has questions, please post them here :) Happy mid quarter scoring!

**Comment by jessicaschilling** [comment]
**Documentation & Developer UX update**
We're ticking along quite well! All OKRs are mid-Q actual of at least 0.5, with the exception of the prioritized features list for our revamped docs platform — this is due to our team rallying on some of our more time-sensitive OKRs, such as releasing the (almost implemented) goal-based quiz on the front of ipfs.io (we want to release this ASAP in order to gather usage metrics that can feed into how we prioritize upcoming IPFS docs-production efforts). Note, though, that the actual platform evaluation for the new docs platform is going great — @cwaring has done a fantastic job evaluating candidates and is currently spiking on a test build for our lead candidate platform.

Only real area of uncertainty is on the hiring front; while we've done quite a bit of work in sourcing and interviewing for our new documentation and technical content strategist, it's impossible to tell whether we'll be able to find, recruit and onboard the right candidate by the end of the quarter. We're continuing with our best efforts, and will be receiving some help from Danielle and company, so the outlook continues to trend positive.

Note: I'm also adding @terichadbourne as an assignee on this issue, since some of her [ProtoSchool OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q3.md) roll up into the docs team's OKRs. (Teri, please update the [primary OKR spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909) when you get a chance, and comment on this issue -- thanks!)

**Comment by terichadbourne** [comment]
**ProtoSchool Update**

@fsdiogo and I have made great progress on a number of our highest-priority ProtoSchool items for the quarter, including: 
-  linking back and forth between ProtoSchool and other IPFS-related docs/websites/repos, including from our new resources pages (shipped)
- setting up Countly analytics (basics shipped, event tracking shipping shortly)
- enabling multiple-choice lessons (shipped)

Our highest-priority untackled items that we still hope to complete this quarter relate to new content development: 
- analyzing IPFS Camp content for inclusion in ProtoSchool
- building non-MFS file tutorial

Given the anticipated halving of our capacity starting at the end of next week (😥), we expect to be unable to complete our ProtoSchool OKRs this quarter. As we reprioritize and shift responsibilities, the following higher-priority items are likely to be fully dropped or only partially completed (as will some lower-priority ones):
- enabling libp2p tutorials 
- splitting the decentralized data structures tutorial in two 
- reviewing alternative online coding education platforms to determiner whether we should incorporate an existing tool or continue to improve our custom system

As @jessicaschilling mentioned, there's a single line on the docs tab of the IPFS OKR spreadsheet that represents the sum of all of our IPFS docs-related efforts for ProtoSchool as a single P1 line item. You can **view our [ProtoSchool Q3 OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q3.md)** for full priority and scoring details and an indication of which items we think of as relating to IPFS docs. 

I've used the same weighted formula that the spreadsheet uses to break down overall mid-quarter and projected scores for our ProtoSchool OKRs as a whole as well as by docs-related and non-docs-related filters, and you can see from these numbers that we've leaned heavily toward addressing the docs-related items and have been tackling our P0 items first.  (Note that our projected scores assume either no capacity backfill this quarter or a re-allocation of time to onboarding new contributors.)

|   | Mid-Q | Projected | 
|---| ---| ---  |
| **All KRs** | **0.5** | **0.7** | 
| IPFS Docs KRs | 0.6  | 0.9 |
| Other KRs |  0.2 | 0.4  |

**Comment by autonome** [comment]
### Project Operations

_The IPFS Community is informed of relevant news in a timely manner_

We are proactively updating the community about important news and project progress, and shipping at least one post per month! For this goal, I'm counting posts that are not release posts or weekly updates. Check out: [IPFS Camp Recap](https://blog.ipfs.io/2019-07-08-ipfs-camp-recap/), [Recapping IPFS in Q2](https://blog.ipfs.io/98-ipfs-weekly-49/), [IPFS Camp Recordings](https://blog.ipfs.io/2019-07-22-ipfs-camp-content-first-batch/), [Q3 Task Force Remix](https://blog.ipfs.io/2019-07-31-operation-task-force/), the [GREAT CALAMITY CIRCUMVENTION ASSEMBLY](https://blog.ipfs.io/2019-08-12-great-calamity-circumvention-assembly-at-ipfs-camp/) and the [Improved IPFS Release Process](https://blog.ipfs.io/2019-08-14-ipfs-release-process/). We also have additional goals around a content plan and schedule, communications plans to have in-hand, and community comms metrics which are mostly not yet started, but appear possible to achieve by EOQ at this rate.


*Collaborations are systematized and prioritized*

This work breaks down into two main areas - collaborations process, and priority collaborations.

For the process work, we've finished planning for a very simple pipeline to help manage our collaborations and opportunities, and a way to keep track of projects and products that use IPFS. The main components are a user registry, a collaborations policy, a collaborations pipeline tool, and the operations and communications to drive and support the overall effort. We're prototyping the registry and pipeline in Airtable, and work is on track.

The collaborations we're supporting this quarter are Brave, Opera and ENS integrations and the relevant work there is mostly on-track. There are some unscored items due to summer vacations, so I'll wheel back around and update this once people are in the office again.

Primary work to support these collaborations:
* IPNS over DNS
* JS-IPFS embedded node in Brave
* IPFS-based ENS service
* Engineering support for Opera's implementation

*Lower priority projects are clearly owned and maintained*

The focus of this work is IPFS Desktop and Web UI. While we're not prioritizing new feature development this quarter for these, it's critical that they keep pace with new Go and JS IPFS releases. We've used this opportunity to revisit how Web UI is shipped in the core releases, to build a view into our overall dependencies and level of test coverage, and reorganized DRIs with Henrique taking charge of these projects' daily operations.

*Project Operations.... Cont'd*

Both the Core Implementation and Research groups have OKRs and we'll post those here once they're scored fully and ready to write up.

**Comment by jessicaschilling** [comment]
Closing this issue since it's been superseded by #1033; feel free to re-open if necessary.
