### ISSUE TITLE
2019 Q4 Planning (and Q3 OKR Scoring) 🎉

### ISSUE THREAD

**Issue by momack2** [ipfs/team-mgmt#1033]
Hello friends and @ipfs/wg-captains!

The end of the Quarter is coming up and with it, time for us to score Q3 OKRs and finalize our plans for Q4! Our aim is to finish grading Q3's OKRs by EOWeek, and then finalize Q4 OKRs by Sept 27th.

@daviddias has done a great job [explaining how this happens in the past](https://github.com/ipfs/team-mgmt/issues/698) and drafted our [Notes on OKR Planning](https://github.com/ipfs/team-mgmt/blob/master/OKR/README.md#notes-on-okr-planning), which is a great primer on how and why we use OKRs.

The TLDR is:

<Scoring>

1. Update scores in the [IPFS Q3 OKRs sheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1681757723) - everyone should fill in the rows that they own
    * `End-Q Actual` - How much progress you made on this KR
    * `Notes on grading` - An update on why you gave it this score (if not obvious)
2. Check the "scoring" box below for your WG
3. Comment on this issue, with a few sentences to recap accomplishments in Q3

<Drafting>

4. Create a PR against your group's OKR doc (creating a new doc if needed) -- https://github.com/ipfs/team-mgmt/tree/master/OKR -- to invite team members and the community to discuss the most important work for the coming quarter. See this past example to give you an idea (https://github.com/ipfs/team-mgmt/pull/799)
5. Once the OKRs are ready, push them to the [IPFS 2019 Q4 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1685270127)
6. Check the "drafting" box below for your WG

If you are new to this whole process, check in with your Working Group colleagues and go through the [issue that covers how we did it for 2019 Q1](https://github.com/ipfs/team-mgmt/issues/792) for context. Please post all your remaining questions so that we make sure to get them answered and improve our docs in the process ✨

**End of Q3 Scoring Checklist:**
- [x] [Bifrost (aka IPFS as a Service)](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1439867466)
- [x] [Testing Infra](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=96566767)
- [x] [Project Operations](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1562851442)
- [x] [Package Managers](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1685270127)
- [x] [Documentation & Developer UX](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909)

**Q4 OKR Drafting Checklist:**
- [x] [bifrost](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1439867466)
- [x] [testing infra](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=96566767)
- [x] [project operations](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1562851442)
- [x] [package managers](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1685270127)
- [x] [docs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909)

If anyone has questions, please post them here :)

**Comment by momack2** [comment]
@jessicaschilling @autonome @Stebalien @raulk @olizilla - It'd be really awesome if each of you could help list here the set of main **Accomplishments** from your team (especially those that *aren't* captured in the OKRs). I'm writing the draft of our Q4 Project Objectives and want to have a slightly more complete list since scoring is still underway. =]

**Comment by jessicaschilling** [comment]
@terichadbourne -- do you mind filling in the end-of-quarter metric and associated notes for ProtoSchool-related docs OKR in the spreadsheet? https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909
Thanks!

**Comment by jessicaschilling** [comment]
**Docs & Developer UX Update**
_(note: ProtoSchool-specific OKR update will be provided separately by @terichadbourne!)_

**Accomplishments**
- Stood up docs team from scratch and iterated upon working methods, meeting structures, agile alignment, project management, planning, etc until we hit the most effective formula for our team (including because this takes work!)
- Completed a [content inventory](https://docs.google.com/spreadsheets/d/1fUsep3keTFrp7TkfiVHcwOdOK0mKvPmdOd5dSFEdhjI/edit?ts=5d6982c8#gid=0) of ipfs.io and selected related materials; used these findings to issue-ize/prioritize tactical fixes, as well as open to discussion/testing/planning larger, more strategic issues
- Brought the [ipfs/docs](https://github.com/ipfs/docs) and [ipfs/website repos](https://github.com/ipfs/website) under active management, including initial issue grooming/reconciliation/prioritization and ongoing management using ZenHub for kanban-style planning
- Closed (as of time of writing) more than 20 [issues](https://github.com/ipfs/docs/issues?q=label%3A%22OKR%3A+Hotfixes%22+is%3Aclosed) identified as tactical "hotfixes" either through the content inventory or through grooming inherited ipfs/docs and ipfs/website issues
- Added a "what do you want to do with IPFS?" [quiz](https://ipfs.io/#get-started) to the front of ipfs.io in order to gauge user goals (and alignment with personae) and stand up an initial framework for passive metrics collection on ipfs.io and IPFS docs
- Added "was this helpful?" [feedback metric](https://github.com/ipfs/docs/pull/265) to all existing content items on docs.ipfs.io to gain initial visibility into overall effectiveness and prioritize individual content items/topics
- Researched competitive landscape and analogous products/services to discuss and spec out a prioritized [features list](https://docs.google.com/spreadsheets/d/1YJ8yuzoNeunVr3ftvm7x2nIKsj7IlTrsfuy71ZnGg6Y/edit#gid=785339355) for a new IPFS docs platform (to be implemented as beta in Q4)
- In parallel, researched and sandboxed options to determine a best-fit platform for the new IPFS docs site 
- Drafted, audience-tested and shipped goal-based [personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf) for key IPFS use cases, to be used in Q4 and beyond for audience alignment and prioritization on existing docs revisions and new docs creation
- As part of many of the above efforts, put into place methodologies for mid-stream user testing, including recruitment, [test planning](https://docs.google.com/document/d/1c2TFeXLFW29a8HYwUq6K9-n8fDg2WhERRIi1CWHMC-8/edit), execution methods, etc
- Got very, very close to hiring a new [Documentation & Technical Content Strategist](https://jobs.lever.co/protocol/e7db2c84-afd7-44a4-9a27-449c751d8289) so that we have the bandwidth to keep building the good things we've researched, planned and spec'd out this quarter (and we may get there yet; watch this space!)

**Challenges**
- Hiring the new docs writer/strategist has been slower than desired due to the very particular nature of the role for which we're recruiting (but we're hoping to wrap this effort up just in time!)
- We lost two team members, one with a bit shorter notice than we might have wanted, and had to take on extra efforts individually (but things are trending up now that we have @dominguesgm on board!)
- Maybe more of a humblebrag than a challenge, but as a net-new team in a previously unaddressed area of IPFSland, we've been challenged in Q3 to implement as much immediately user-helpful stuff as we can while still laying a strategic foundation for mid-term and long-term docs success. Through directly addressing this strategic/tactical balance when creating our Q3 OKRs — and through keeping those OKRs front and center when generating epics, tasks and sub-tasks, and even in our bi-weekly check-ins — we've been able to successfully balance these sometimes-conflicting priorities.

**Q4 spoiler alert!** 
Docs OKRs are being defined/discussed [in PR #1036](https://github.com/ipfs/team-mgmt/pull/1036), if you want to follow along.

_cc @terichadbourne @dominguesgm @cwaring @ericronne to rep the docs team 😄_

**Comment by terichadbourne** [comment]
Adding ProtoSchool-specific notes per @jessicaschilling's request: 

- Accomplishments
   - Added resources pages to all existing ProtoSchool tutorials (and as a standard moving forward) to highlight related ProtoSchool content, and external learning materials in other formats
   - Added extensive bi-directional linking between ProtoSchool, ipfs.io, js-ipfs.io, IPFS and IPLD documentation/repo sites, etc. to ensure better discovery of both ProtoSchool and IPFS docs  
   - Created a multiple-choice lesson format that will allow better engagement and comprehension checks in lessons without coding challenges
   - Transitioned metrics to Countly, enabling page-specific stats and measuring user behaviors (such as completion of lessons and tutorials and correct and incorrect code submissions, heat maps, scroll maps, etc.) that will help us understand learner needs

- Challenges
   - Lost time due to a staffing transition, but very excited to have a new teammate picking up speed quickly

Note ProtoSchool's OKRs (extending beyond just IPFS docs-related pursuits) in our roadmap repo: 
- [Graded Q3 OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q3.md)
- [Q4 OKR draft](https://github.com/ProtoSchool/roadmap/pull/24) (WIP PR)

**Comment by momack2** [comment]
Here is the [**Project-level Priorities doc**](https://docs.google.com/document/d/15A3tuMvCMucJWtDmnsGLy3kzocgpqn5XR1Jvt06Vsd8/edit#) reviewed with cross-project/WG leads last week! 🎉

This documents project level goals for the quarter and relative ranking of priorities between threads. Heads up that our P0 on **landing Testing Infra** might mean that folks on other working groups with go-ipfs / infra capabilities get tapped for 1-2 weeks of fast-paced work in the mid-Oct timeframe to help unblock this! 🙏

Also kudos to @jessicaschilling @Stebalien and @olizilla for having PRs up for Q4 OKRs! @daviddias will be stepping in to do Q4 OKRs for the testing infra team, and I'll step in for project operation (and refine with @autonome when he's back from browsers hack week). 🙌

**Comment by momack2** [comment]
## Project Operations Update

### Accomplishments
- Shipped >90 amazing videos from IPFS Camp and 4+ blog posts to go with!
- Shipped blog post on Q3 team organization / priorities
- Created new collabs user pipeline and triage process
- Created comprehensive user registry in airtable as source of truth for known IPFS users (current and future)
- Ran IPFS/libp2p help desk at EthBerlinZwei in collaboration with Textile and Pinata
- Ran 2 IPFS Camp and 2 protoschool workshops at the Web3 p2p node
- New tools to support people coaches in leveling up on new skills and aligning on best practices 
- “Open Positions working on IPFS” section in the newsletter is getting adoption and creating a community market for “IPFS Skills” 
- Created a user registry and collab triage process
- Js-ipfs and go-ipfs both have new release processes used to roll out changes to the core protocol catching bugs before they reach the wild
- Go shipped 1 patch release and js (has almost) shipped a minor release through the new process
- Js-ipfs shipped a new constructor, support for dnslink, delegated peer and content routing, and more coming in the next release landing EOQ (GC, gossipsub by default, add via async iterators, IPNS and recursive option for ipfs resolve
- Pubsub in the browser (via ipfs-http-client) shipped
- 1-click companion install is softly released in Brave release channel - hoping to get remaining URL bar changes and use of TCP transport/local DNS discovery in time for an awesome demo at DevCon
- Coredns ENS plugin accepted for listing in coredns official directory - blog post pre-DevCon announcing completion along with workshops and presentations at DevCon and aux events

### Challenges
- Fast IPNS (over DNS) got blocked on spec
- Bringing on new contributors to the IPFS core working groups (we’re slow at this!)
- Didn't get to some of our comms/community planning / support goals
- Browser people were on summer holidays and moving slower than expected

See Q4 planning in https://github.com/ipfs/team-mgmt/pull/1042

**Comment by momack2** [comment]
Hey Everyone (especially @olizilla, @daviddias, and @Stebalien) - reminder to merge our OKR planning threads and transfer OKRs to the Q4 spreadsheet: https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1681757723

**Comment by olizilla** [comment]
I've updated the bifrost page on the spreadsheet. I'm going to leave the PR open till @lanzafame  gets back, as I'd like to get his +1s or amends there before closing it.

**Comment by momack2** [comment]
Thanks everyone for updating the [Q4 OKRs spreadsheet](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1681757723)! The video of our All Hands today, recapping all these quarterly priorities and explaining why they're important, is now up on YouTube! 

**Check it out: https://www.youtube.com/watch?v=pPL3ppVnNhQ**
