### ISSUE TITLE
Joint Go Core and JS Core Meeting

### ISSUE THREAD

**Issue by Stebalien** [ipfs/team-mgmt#733]
At this weeks go all hands, we discussed the need for better cross js/go communication. Current proposals:

* Hold a separate meeting every other week to discuss interop issues.
* Join the existing meetings every other week.
* Join the existing meetings every week, optionally with a break-out at the end to js/go groups.

**Comment by djdv** [comment]
I wonder if we could avoid the necessity of more people in more meetings by just sharing a common, global agenda, that is checked by each sync host in addition to their own specific sync agenda.

For instance a document that has a section for teams that wish to pass arbitrary messages to each other on a weekly basis, that in turn would lead to ad hoc syncs as needed instead of scheduled.
```
go-ipfs:
  - @someone wants to know from the JS team what's the deal with airline streams? Please reach out to them.

js-ipfs:
 - We think the go team are really nice people
 - There seems to be an interop problem between go-ipfs and js-ipfs regarding X, please reach out to @someoneelse to schedule a meeting between teams

libp2p:
 - This quarter we introduced this feature that people may be interested in using. Points of contact are libp2p/issues/##, @x, @y,...
```

Items would be trimmed/removed as necessary and not just grow forever.

This may be something to disucuss AFTER an initial meeting though. I'm curious what kind of frequency is needed/desired for cross team syncs.

**Comment by diasdavid** [comment]
Ping @ipfs/javascript-team

**Comment by jacobheun** [comment]
I think it would be helpful to better understand what the actual points of frustration are, as they'll likely have different solutions.
* Are there issues knowing what each team is working on? 
* Are the communication issues isolated to interop?
* Are we looking for a regular time for us all to be able to sync on a specific agenda?
* Something else?

One thing I think we could be better about doing is notifying *and* responding/collaborating on cross language work.

**Comment by momack2** [comment]
I see 3 different needs to be solved by these weekly meetings:
1. Need for go/js IPFS cross-communication and visibility of features/design choices
2. Need for IPFS/Libp2p/IPLD cross-communication (especially important within language focus when coordinating changes)
3. Need for wg-specific status updated, problem solving, discussion, visibility/resolution of blockers, etc

Currently we have "Core Dev" meetings for go and js (which includes all IPFS/Libp2p/IPLD core developers in each lang). There is also a Libp2p biweekly and an IPLD biweekly that recaps status updates and dives into design discussions for each specific area. 

Right now, we use our "Go Core Dev" meeting as the sole venue for go-ipfs status updates and feature/project discussion (and same for the js meeting). This enables **needs 2 & 3** for the go-ipfs team - however that discussion/update might be less useful/relevant for Libp2p/IPLD attendees. We don't currently have a meeting venue for **need 1**.

Potential solutions:
- Host an additional biweekly "Core IPFS" call for js/go IPFS status updates and cross-language discussion (like the Libp2p and IPLD calls) - _(solves **need 1** and moves some IPFS-focused discussion out of existing meeting)_
- Merge the existing go and js core weekly calls and create separate venues for go-ipfs and js-ipfs status updates/discussion - _(merged meeting solves **needs 1 & 2**, new meetings solve **need 3**)_

**Comment by mikeal** [comment]
Because of the size of both teams there isn't room to get through more than a weekly standup in the current 30m calls.

This means it isn't feasible to use a similar format in a meeting with both groups. I like the idea of "working group" updates but I worry that this will end up being overly focused on the JS side since there are more working groups.

If we drop the "updates" format entirely and go with a more formalized agenda designed to discuss specific cross-team issues then we need someone to chair the meeting who will build that agenda and potentially moderate the call.

**Comment by daviddias** [comment]
Check it out #992 . Dreams do come true :D
