### ISSUE TITLE
Rethink gui and in-web-browsers teams as ipfs-apps

### ISSUE THREAD

**Issue by olizilla** [ipfs/team-mgmt#752]
We're not currently getting a lot of value from splitting the ipfs-gui and ipfs-in-web-browsers efforts. We attend the same stand up, and we have 4 dedicated team members across the two groups.

I'd like to propose we try merging ipfs-gui and ipfs-in-web-browsers under the banner of **ipfs-apps**. Our focus would remain the same. The ipfs-in-web-browsers effort and the products (desktop, webui, companion) under the ipfs-guis remit would continue as before. Having 1 team present as 2 working groups is just creating extra work for us right now.

Going further, i'm feeling really silo'd from the dynamic-data team right now, and I'd like to start a discussion around rethining the ipfs-apps team as pulling together all the pieces needed to build apps on top of ipfs; for our partners, for our products (desktop etc), and for the suite of distributed tools that our working groups will need to keep co-ordinating as we grow.

**Comment by olizilla** [comment]
To clarify, I'm proposing this for 2019 Q1, and I don't want this to affect the current roadmap planning.

I'm working on the assumption that if there is interest for merging, we'd be able to merge our roadmaps after the fact, and see the team as having a collection of shared goals / projects / endevours

**Comment by mikeal** [comment]
Would the projects still remain separated? There's a few people from browser vendors watching the ipfs-in-web-browsers project specifically so I wouldn't want to make it harder for the to interact with that work.

**Comment by lidel** [comment]
I am happy we are having this discussion.

Been thinking about this since yesterday, after some good feedback from Oli and David. 
There is indeed a big overlap on the UI side between WB (In Web Browsers) WG and GUI WG.
_However_,  we also have some overlap with other groups as well (eg. JS Core WG, Community WG, DDC WG), which means merging with GUI WG may not solve all the problems, or even create new ones.

I agree, it  feels awkward to find someone else already has an OKR similar to one from your WG, but that may be a signal we should get better at separating the concerns. 

For example, now that we have Design WG we could rename GUI WG to Apps WG (or not) and improve focus by making it directly responsible for _maintenance, UI/UX implementation and end user happiness_ of not only ipfs-desktop, ipfs-webui, ipfs-companion, but also peer-pad and discussify. Having everything under one umbrella would not only optimize resources, but guarantee we have a coherent UX. 

Just like @pgte suggested WB or DDC WGs would no longer be directly responsible for user interfaces and could then focus OKRs on producing specs, docs, APIs and libraries for GUI WG as their "client".

**Comment by meiqimichelle** [comment]
This is a great conversation. I want to try to summarize the points so far:

- We are small teams, sometimes 100% overlapping. From a people-time perspective, we perhaps could combine certain conversations into one meeting instead of several and use people's time more efficiently (and therefore move faster towards our goals!).

- We'd like to see better user experience coordination across our user-facing concerns: ipfs-desktop, ipfs-webui, ipfs-companion, peer-pad, and discussify. aka, there should be a better way to pull together all the pieces needed to build apps on top of ipfs, and it is not helpful to keep these conversations separate. In fact, the status quo is probably *negatively* impacting our work because our UX will be less consistent than it could be.

- Maybe by doing this, we'll have a better separation of concerns so that solutions across our IPFS WGs are not tightly coupled, and this will provide a 'customer' for our specs, docs, APIs, and libraries to keep them honest.

MHz thoughts on these points:
**+100 to this ideas in this issue!** It's been a struggle since I started working on IPFS to pull user experience threads through our work, and recognizing that those pieces *should* be pulled together into one cohesive story, and figuring out the best way to support that, is the only way we're going to make a great user experience and make people happy. In short: YAAASSSSSS please let's re-arrange so we can do this better!

At a working-group-team-group-of-humans-working-together-level (aka, how to actually make this happen, given our existing WG structures), I suggest taking a step-by-step approach:

1. We should all agree that we should form some sort of structure that lets ipfs-desktop, ipfs-webui, ipfs-companion, peer-pad, and discussify UX work together. I think we've actually already done this in this chain -- we all seem to want this. ✅ 

2. Some group of people (perhaps all the people working on those projects, or existing team leads/WG Captains/not sure who leads these) should articulate one set of UX goals across ipfs-apps. Call it the `ipfs-apps huddle` for lack of other term. This may be as simple as finishing the work already started in the IPFS Roadmap where we're looking through each others v0 workplans to better understand where overlap is, de-duping as needed, and aligning work. Out of this, we should have a comprehensive UX vision for ipfs-apps. This is the "where we want to be", not the "how we're going to get there".

3. Once we have the 'where we want to be', we can do the 'how we want to get there' across the projects. For example, as a person trying to work on user experience at PL, I don't know right now where to go to understand the status of all these ipfs-app threads. If I understood that better, I (and the Design Team) would definitely have opinions about how to help move forward.

**Other thoughts that aren't direct next steps**

Whatever we decide on the other side of this discussion, I'm sure it will be related to this other thread going on in [this LabOS issue](https://github.com/protocol/LabOS/issues/36) about how to structure the org so we can do great experience design work. The long story very short: designers should be embedded on project teams, and design should not pulled out as a separate service team. There should be *designers* on *projects*, and the Design Team is there to support the *designers* themselves. 

In the context of this issue, we could have an IPFS Apps UX WG, and that WG could coordinate all the user-facing work we do (ie, it could entirely contain projects called ipfs-desktop, ipfs-webui, ipfs-companion, peer-pad, and discussify). But we would not re-name the Design Team to be a project-coordinating team for one part of IPFS -- it is meant to be a different thing.

And, one final piece of input (food for thought!) as we get better coordination across IPFS design work -- when I worked staffing teams for service design consulting and development, the minimum we'd staff to any design-and-dev project was three fairly full-time people, and that was running it very lean to produce an MVP that had some amount of user research and usability testing so that we could build things that people can use and are happy with. That tended to be a PM/user-research role, a UX/UI designer, and a developer, depending on project needs. I don't know how many people we're splitting across all these ipfs-app projects right now, but we may be understaffed for the amount of work we hope to do if our goal is to produce great user experiences. 

I'm not raising this as something we need to address right now, I just wanted to add it to the back of people's minds as a level-set, in case folks on this chain hadn't worked on projects with strong user research and user experience focus before. I figured folks might not all have had experience in what _end user happiness_ means, in terms of people-time to do that work. This coordination work we're trying to do across our ipfs-apps projects I'm sure will help us figure out how close or far we are from getting to where we want to go.

**Comment by daviddias** [comment]
What I'm reading (and hearing from WG discussions) is something that looks like this:

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1211152/48697111-b7464100-ebdb-11e8-8381-0717a38e44aa.png">

Is this illustration correct?

**Comment by pgte** [comment]
@daviddias that looks good, even though the apfs-apps may well interact with the "Hard" Core level (like, for instance, when using direct IPFS or libp2p features).

One question: is there an ETA for having a discussion / decision? Should we decide on this before the next 2019 OKR milestone?

**Comment by daviddias** [comment]
> One question: is there an ETA for having a discussion / decision? Should we decide on this before the next 2019 OKR milestone?

I'm not as worried because this proposal is not about stopping/starting new work, it would just be a shuffle of coordination.

**Comment by olizilla** [comment]
I'll sumarise this now very long thread, highlight the opportunities and risks, and propose some actions, later today.

**Comment by olizilla** [comment]
There are many related issues here, I won't tackle them all now...

- Reporting and management burden on small WGs.
- A desire to optimise WG responsibilities / reduce overlap.
- A desire to define WGs as clients of other working groups.
- A contrary desire to reduce the silo-ing between WGs
- UX/UI coherence across products
- Lifecycle of a product... when should a WG hand it off?
- Optimum team size

My gut feeling right now, and from talking to @lidel and @daviddias is

- Merging in-web-browsers and GUI to reduce reporting burden isn't a good route. Growing those teams is still the goal. In the meantime we really need a volunteer to help with in-web-browsers, while we boot up the hiring process.
- Merging GUI and DDC would reduce silo-ing but would leave us with a team of ~10 people which I think is too big. I should join DDC calls to get more involved.
- Each working group owning "a product" is a good thing. GUI is building out components for Web UI. DDC is trying out and refining their apis in real apps. in-web-browsers knows all the details of getting IPFS into the browser _because_ they're/he's building companion.

It's tempting to draw layers, and a define a working group as a client of another, but my concern is that will increase the silo-ing, that i'm feeling right now. To @meiqimichelle's point about "where do we want to be", I'm thinking less _ipfs-apps is a client of ddc_ and something more, deliberately reciprocal, where each WG has some output that boosts the others...

![ipfs-p2p-wg](https://user-images.githubusercontent.com/58871/48921088-331ee280-ee95-11e8-97da-6434a1ce0237.png)

I'd like the GUI team to provide a component library and UX patterns that the DDC enjoy using and reduces their UI workload, so they can spend more time on the interactions with the api. Discussify already has a good foundation, but peer-pad and future apps would benefit. It would be rad to figure out use-cases for building features from the DDCs libs to boost Web UI and Desktop.

Likewise In web-browsers defines the window.ipfs api and the ipfs-provider lib that GUI and DDC apps should use and Companion would benefit from using GUIs UI component library and the DDCs libs too.

This is a lot less radical than the initial proposal, but getting much more explicit about how we boost each other and solve each others pain-points seems like a win.

@pgte do you have time for a call tomorrow. I want to get a good sense of what your scenario is, before push this further or open us all up to too much more bike shedding!

**Comment by pgte** [comment]
@olizilla and I talked, and after some reflection, here is what I think:

In contrast to the "service layer" model, I think this virtuous feedback loop would be very beneficial for both teams, keeping both working groups grounded.

One of the OKRs in the DDC working group is about collecting a library of UX patterns for Apps, as we discover and distill them. In this model, this clearly belongs where it should: in the GUI working group.

I also like having a more diverse set of PoC apps, and @olizilla is a clear good source of these ideas and requirements, which will help drive the DDC forward!

**Comment by daviddias** [comment]
@olizilla @pgte, out of this conversation, can any of you articulate what are the next steps (proposed changes, improvements, etc)? So that it is clear to everyone what the final verdict is.

**Comment by daviddias** [comment]
> I also like having a more diverse set of PoC apps, and @olizilla is a clear good source of these ideas and requirements, which will help drive the DDC forward!

An excellent source and the way to increase the app portfolio on top of the Tech the IPFS Org produces, it is to look into and support the community directly.

Today you have: https://github.com/ipfs-shipyard/peer-star-app/network/dependents

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1211152/48978764-b401f800-f0a8-11e8-8765-8e01c802ef96.png">

Not massive as https://github.com/ipfs/js-ipfs/network/dependents or https://github.com/ipfs/js-ipfs-api/network/dependents, but it is a good start. 

The next steps should include reaching out to these and all the other ones we know about to encourage them to use this new base layer, peer-star-app, to solve their DApp problems.

**Comment by lidel** [comment]
Some background on the outcome for in-web-browsers WG:

- During highly valuable discussions with @olizilla  and @daviddias we looked at two hypothetical ways to move forward: 
  - (A) growing the in-web-browsers team 
  - (B) closing the WG and moving responsibilities to JS Core and IPFS GUI
- We are in agreement it makes sense to:
  - **Continue in-web-browsers as a separate WG**, at least in 2019
    - A dedicated WG keeps our focus and ensures we don't miss opportunities in 2019
    - We will revisit (B) in 2020+ if it feels having a separate WG served its purpose or starts producing diminishing returns
  - **Grow the in-web-browsers WG** - both team and community engagement to be able to tackle more problems at once

**Comment by daviddias** [comment]
With both https://github.com/ipfs/team-mgmt/issues/752#issuecomment-441606732 and https://github.com/ipfs/team-mgmt/issues/752#issuecomment-442417974 comments as conclusions, do we feel we all got closure on this discussion and we understand the path ahead for the time being? Is it ok to close the issue now?

**Comment by olizilla** [comment]
I do. As I started this adventure, I'll close it out. I'll be working out the GUI team Q1 OKRs next week, and I intend to work with DDC, Community, and in-web-browsers, go/js-ipfs  to make sure we're building things that will be as useful as possible.

Feel free to re-open if you have more ideas on this thread!
