### ISSUE TITLE
Weekly Calls: Move historical notes out of the document we use every week

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#810]
Proposal: Stop accumulating meeting notes in [the google document we use each week](https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit). Keep that document small and easy to load. Move historical notes to Github.

Actions: 
- Delete old meeting notes from the document (make sure they're in github first!)
- Establish process to make sure all call notes are always copied to Github each week and deleted from the google doc
- Direct people to github as the official reference point for historical meeting notes. 

Why
- As the document gets bigger, it takes longer to load.  
- Github, not google docs, is our official place to accumulate meeting notes.

**Comment by flyingzumwalt** [comment]
cc @pkafei

**Comment by pkafei** [comment]
@flyingzumwalt We have do have a historical copy of IPFS Weekly Call notes on[ github](https://github.com/ipfs/team-mgmt/tree/master/meeting-notes/2018). In the future, we are thinking of taking notes on [Peer Pad](https://github.com/ipfs-shipyard/peer-pad), instead of [Google Docs](https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit#heading=h.hz5t61tdc5r6).

**Comment by daviddias** [comment]
@pkafei I believe @flyingzumwalt's proposal, IIUC, is to delete the notes from Google Docs once they have been ported to Github, so that Google Doc stays small and loads fast to everyone

**Comment by momack2** [comment]
Deprecating this suggestion since we haven't acted on it in 6 months.
