### ISSUE TITLE
Go-IPFS meeting format proposal

### ISSUE THREAD

**Issue by Stebalien** [ipfs/team-mgmt#827]
To try to save time for deeper discussions, @momack2 and I would like to propose a new meeting format.

**Meeting**

1. Blockers/asks (no updates)
2. Announcements
3. Agenda Items

**Async**

- Every large endeavor gets a meta issue ("epic issue").
- Updates are posted in these issues.

**Comment by momack2** [comment]
To achieve this format, I'd propose moving away from the individual update structure of the meeting notes and more toward a list of efforts that are divided by project/type. This would make it harder to see what one particular individual has worked on - but easier to see the project progress. We could put names next to projects if that helped, but I'd imagine only one person would summarize the progress in that project in the last week. Sample reformat if we decide to go this route:

# meeting 3

## blockers/asks
- (erik) I need review on X
- (molly) Can folks comment on this issue
- (steb) Who can pair on Y?

## announcements
- OKR meeting next week

## project updates
### Datastore _(name)_
- Updated X benchmarks
- Working on a change to Z
### Bitswap _(name, name)_
- PRs X and Y Submitted
- Waiting on review for Z
- Starting work on 123
### CoreAPI Improvements _(name)_
- new PRs merged
### base32 cid _(name)_
- need review on X
- javascript did Y
### other project _(name)_
- no update this week
### < insert other projects here if they get worked on >

## agenda
- discuss meeting format for next week

**Comment by hannahhoward** [comment]
@momack2 I agree but I'd focus specifically on top level priorities areas based on OKRs rather than specific projects - i.e "data transfer speeds", "adding and providing large data sets", "datastore efficiency", "go-ipfs ease of integration", "go-ipfs project maintaince/process", "outstanding efforts" -- many of these map to a specific project but still seems useful to operate on a priority level

**Comment by Stebalien** [comment]
@hannahhoward what if we do both? That is, we cover the priorities and, while doing so, make sure to touch on each "initiative" within each priority. I'd still like to touch on each initiative so everyone's clear on the status, blockers, priorities, etc.

But yeah, we should definitely make sure to focus on the priorities.

**Comment by eingenito** [comment]
I think this is a great idea and I have a couple of questions. I like the emphasis on keeping a set of meta issues updated with status. I think that could be really helpful for people who don't attend the meeting or for things that happen during the week and go unmentioned. 

I also like the shift to talking about important initiatives as a thing (or things) - I think it can make people more aware of priorities and lead them towards focusing on top priorities which I think would be good in general for go-ifps. 

And questions:

Is the goal to be inclusive of everyone in the meeting and therefore to have people reframe their week's work from 'Here's what I did' to 'Here's the progress that I made on this initiative that has a name and some shared context'? Meaning is it changing the narrative structure of the current meeting content so that people can follow it better?

or ...

Are we talking about eliminating some/much of the current content of the meetings. For instance - if people worked on things outside of a set of curated (and relatively stable) top level priorities that's fine, but we don't need to review that work as a team? 

Also an overlapping question - I know that libp2p has a separate weekly (I think?) meeting - would we exclude libp2p progress from our meeting and turn it more formally into a go-ipfs meeting? And then follow on question - what about IPLD and @aschmahmann's work? 

And do we have a default topic that we'd like to discuss each week with the time that we save (assuming that's the goal) - like should we review top priority issues in the backlog and see who might have bandwidth over the next week to take them on?

**Comment by aschmahmann** [comment]
@eingenito @momack2

As someone on the periphery of go-ipfs, it is nice to see where people are spending their time/which things are currently being worked on, as well as to hear/give updates from other WGs that might be relevant. However, given that sync time is valuable and it seems like the consensus is to use it largely for discussions, maybe a solution is to have people enter their updates into the shared document a little earlier and then have a block of time to allow the group to ask questions on the updates. The hypothesis here is that A) maybe "pulling" the information from people is more efficient than "pushing" it and B) it may encourage people to write updates that are more informative

I've found sitting in on the meetings of various WGs to personally be very informative and helpful, as well as taking some of the cross WG communication load off of the WG leads. I don't know what the best way is to keep the meetings both go-ipfs focused and inclusive of cross-team attendance, but I'm up for whatever experiments you'd like to try out.

**Comment by eingenito** [comment]
@aschmahmann I have a hope/expectation that people joining to get context on the go-ipfs project will get _more_ out of a discussion of progress on initiatives than they currently do because it just fames work in a more understandable way. 

@momack2 I really like your answers. I have felt like the meeting (as run by me) hasn't been great at encompassing everyone (meaning ipld, libp2p etc.) and yet hasn't explicitly focused on go-ipfs. And given that there are separate meetings for the other projects I'd like for it to focus on go-ipfs. 

It also makes sense that discussing the top level initiatives is what we should be spending our sync time doing. I'm curious if we can transition the 30 minutes from a status report style meeting to let's dig into important questions as a team and make meaningful progress on them. 

@aschmahmann your idea about handling updates via a shared document (like maybe the weekly notes and strategic linking to github epics) well beforehand and then making room for questions makes a lot of sense to me. And it makes me think that to get anywhere past the 'status report' stage in 30 minutes we're going to have to prep discussions a bit to provide context to the people not working directly on a topic. 

Maybe we can discuss that at next week's meeting :)

**Comment by eingenito** [comment]
@ipfs/go-team - we tried a version of this in today's (01/14/2019) meeting. I thought it was a little rough but an improvement. Anyone have feedback?

There was a little discussion in the meeting notes:

>dislike, suggests each person is working on one thing, and also that whoever drafted outline knows what every one of those things is before hand, which begs the question doesn't it?
>
>Good points - should feel free to add initiatives, and should feel free to contribute to/discuss more than one initiative. 
>  - advantage - we have a forum for "what is the plan for this initiative" that we didn't have a way to discuss synchronously before
>  - downside - not clear where individuals should put "wins" or "updates from other teams" that are valuable but not associated with a specific initiative

**Comment by momack2** [comment]
Feedback delivered to me directly:
- focusing directly around go-ipfs initiatives didn't leave space for important cross-project updates that need visibility and feedback from larger forum in this meeting (vs more detailed discussion happening in the other team biweekly)
- totally makes sense to reduce speaking time on litany of tasks accomplished, but it's nice/useful to save a little room for "key wins" positivity stuff :)
### **suggested solution**: 
Add a "wins" and/or "updates from other teams" section and locate it near the end _(I've taken a pass at adding this section to this week's template - let's see how that goes!)_
- important note: switching speaker tends to take a second longer in video calls than IRL meetings, so switching back and forth can be problematic.  Doing a wins sections where everyone that's proud of something does one sentence would have a lot of those switch costs - so perhaps we need a single person to summarize, or just read async if there aren't any specific questions

**Comment by eingenito** [comment]
@Stebalien / @momack2 okay to close this?

**Comment by Stebalien** [comment]
SGTM.
